# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class CoderOutput(BaseModel):
    files_to_change: typing.List["FileChange"]
    summary: typing.Optional[str] = None

class ConversationMessage(BaseModel):
    role: typing.Optional[typing.Union[str, str]] = None
    content: typing.Optional[str] = None

class FileChange(BaseModel):
    file_path: typing.Optional[str] = None
    blocks: typing.List["SearchReplaceBlock"]
    explanation: typing.Optional[str] = None

class FileInfo(BaseModel):
    file_path: typing.Optional[str] = None
    file_content: typing.Optional[str] = None

class SearchReplaceBlock(BaseModel):
    search: typing.Optional[str] = None
    replace: typing.Optional[str] = None
    language: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
