# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (13)
# #########################################################################

class ChatGPTOutput(BaseModel):
    response: typing.Optional[str] = None
    tool_call: typing.Optional[typing.Union["SearchWebTool", "FetchUrlTool"]] = None
    requires_tool: typing.Optional[bool] = None

class CodebaseContext(BaseModel):
    file_tree: typing.Optional[str] = None
    related_files: typing.List["RelatedFile"]
    project_language: typing.Optional[str] = None
    project_framework: typing.Optional[str] = None

class CoderOutput(BaseModel):
    thinking: typing.Optional[str] = None
    files_to_change: typing.List["FileChange"]
    additional_files_to_check: typing.List[str]
    summary: typing.Optional[str] = None

class ContentBlock(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[str] = None
    content: typing.Optional[str] = None
    structured_data: typing.Optional[typing.Dict[str, str]] = None
    semantic_tags: typing.List[str]
    context: typing.Optional[str] = None
    page_number: typing.Optional[int] = None
    position: typing.Optional[int] = None

class ConversationMessage(BaseModel):
    role: typing.Optional[typing.Union[str, str]] = None
    content: typing.Optional[str] = None

class FetchUrlTool(BaseModel):
    tool_name: typing.Optional[str] = None
    url: typing.Optional[str] = None

class FileChange(BaseModel):
    file_path: typing.Optional[str] = None
    blocks: typing.List["SearchReplaceBlock"]
    explanation: typing.Optional[str] = None

class FileInfo(BaseModel):
    file_path: typing.Optional[str] = None
    file_content: typing.Optional[str] = None

class PDFPageDocument(BaseModel):
    page_summary: typing.Optional[str] = None
    content_blocks: typing.List["ContentBlock"]
    key_entities: typing.Optional[typing.Dict[str, typing.List[str]]] = None
    metadata: typing.Optional["PageMetadata"] = None

class PageMetadata(BaseModel):
    page_number: typing.Optional[int] = None
    has_continuation_from_previous: typing.Optional[bool] = None
    continues_to_next: typing.Optional[bool] = None
    section_name: typing.Optional[str] = None

class RelatedFile(BaseModel):
    file_path: typing.Optional[str] = None
    relationship: typing.Optional[str] = None
    relevant_excerpt: typing.Optional[str] = None

class SearchReplaceBlock(BaseModel):
    search: typing.Optional[str] = None
    replace: typing.Optional[str] = None
    language: typing.Optional[str] = None

class SearchWebTool(BaseModel):
    tool_name: typing.Optional[str] = None
    query: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
