# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ChatResponse": types.ChatResponse,
    "stream_types.ChatResponse": stream_types.ChatResponse,

    "types.CodebaseContext": types.CodebaseContext,
    "stream_types.CodebaseContext": stream_types.CodebaseContext,

    "types.CoderOutput": types.CoderOutput,
    "stream_types.CoderOutput": stream_types.CoderOutput,

    "types.ContentBlock": types.ContentBlock,
    "stream_types.ContentBlock": stream_types.ContentBlock,

    "types.ConversationMessage": types.ConversationMessage,
    "stream_types.ConversationMessage": stream_types.ConversationMessage,

    "types.FetchUrlTool": types.FetchUrlTool,
    "stream_types.FetchUrlTool": stream_types.FetchUrlTool,

    "types.FileChange": types.FileChange,
    "stream_types.FileChange": stream_types.FileChange,

    "types.FileInfo": types.FileInfo,
    "stream_types.FileInfo": stream_types.FileInfo,

    "types.PDFPageDocument": types.PDFPageDocument,
    "stream_types.PDFPageDocument": stream_types.PDFPageDocument,

    "types.PageMetadata": types.PageMetadata,
    "stream_types.PageMetadata": stream_types.PageMetadata,

    "types.RAGTool": types.RAGTool,
    "stream_types.RAGTool": stream_types.RAGTool,

    "types.RelatedFile": types.RelatedFile,
    "stream_types.RelatedFile": stream_types.RelatedFile,

    "types.SearchReplaceBlock": types.SearchReplaceBlock,
    "stream_types.SearchReplaceBlock": stream_types.SearchReplaceBlock,

    "types.SearchWebTool": types.SearchWebTool,
    "stream_types.SearchWebTool": stream_types.SearchWebTool,

    "types.WriteFileTool": types.WriteFileTool,
    "stream_types.WriteFileTool": stream_types.WriteFileTool,


}