# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (14)
# #########################################################################

class ChatGPTOutput(BaseModel):
    response: str
    tool_call: typing.Optional[typing.Union["SearchWebTool", "FetchUrlTool"]] = None
    requires_tool: bool

class CodebaseContext(BaseModel):
    file_tree: str
    related_files: typing.List["RelatedFile"]
    project_language: str

class CoderOutput(BaseModel):
    thinking: str
    files_to_change: typing.List["FileChange"]
    additional_files_to_check: typing.List[str]
    summary: str

class ContentBlock(BaseModel):
    id: str
    type: str
    content: str
    structured_data: typing.Optional[typing.Dict[str, str]] = None
    semantic_tags: typing.List[str]
    context: str
    page_number: int
    position: int

class ConversationMessage(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    content: str

class FetchUrlTool(BaseModel):
    tool_name: typing_extensions.Literal['fetch_url']
    url: str

class FileChange(BaseModel):
    file_path: str
    blocks: typing.List["SearchReplaceBlock"]
    explanation: str

class FileInfo(BaseModel):
    file_path: str
    file_content: str

class PDFPageDocument(BaseModel):
    page_summary: str
    content_blocks: typing.List["ContentBlock"]
    key_entities: typing.Optional[typing.Dict[str, typing.List[str]]] = None
    metadata: "PageMetadata"

class PageMetadata(BaseModel):
    page_number: int
    has_continuation_from_previous: bool
    continues_to_next: bool
    section_name: typing.Optional[str] = None

class RelatedFile(BaseModel):
    file_path: str
    relationship: str
    relevant_excerpt: str

class SearchReplaceBlock(BaseModel):
    search: str
    replace: str
    language: str

class SearchWebTool(BaseModel):
    tool_name: typing_extensions.Literal['search_web']
    query: str

class ToolResult(BaseModel):
    name: str
    success: bool
    output: typing.Optional[typing.Union[str, typing.Dict[str, str]]] = None
    error: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
