# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CoderOutput": types.CoderOutput,
    "stream_types.CoderOutput": stream_types.CoderOutput,

    "types.ConversationMessage": types.ConversationMessage,
    "stream_types.ConversationMessage": stream_types.ConversationMessage,

    "types.FileInfo": types.FileInfo,
    "stream_types.FileInfo": stream_types.FileInfo,


}