# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (12)
# #########################################################################

class ChatResponse(BaseModel):
    response: str
    tool_call: typing.Optional[typing.Union["SearchWebTool", "FetchUrlTool", "RAGTool", "WriteFileTool"]] = None
    requires_tool: bool

class CodebaseContext(BaseModel):
    file_tree: str
    related_files: typing.List["RelatedFile"]
    project_language: str
    project_framework: typing.Optional[str] = None

class CoderOutput(BaseModel):
    thinking: str
    files_to_change: typing.List["FileChange"]
    additional_files_to_check: typing.List[str]
    summary: str

class ConversationMessage(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    content: str

class FetchUrlTool(BaseModel):
    tool_name: typing_extensions.Literal['fetch_url']
    url: str

class FileChange(BaseModel):
    file_path: str
    blocks: typing.List["SearchReplaceBlock"]
    explanation: str

class FileInfo(BaseModel):
    file_path: str
    file_content: str

class RAGTool(BaseModel):
    tool_name: typing_extensions.Literal['rag']
    query: str
    context_source: typing.Optional[str] = None

class RelatedFile(BaseModel):
    file_path: str
    relationship: str
    relevant_excerpt: str

class SearchReplaceBlock(BaseModel):
    search: str
    replace: str
    language: str

class SearchWebTool(BaseModel):
    tool_name: typing_extensions.Literal['search_web']
    query: str

class WriteFileTool(BaseModel):
    tool_name: typing_extensions.Literal['write_file']
    file_path: str
    content: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
